spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: liu1998
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#      jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCL
#      username: system
#      password: liu1998
#      driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 47.107.32.83
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: liu1998
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）x
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 1000


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

